# Arc 3 - Static data
# All restaurant data stored here

RESTAURANTS = [
    {
        "id": 1,
        "name": "FitBite",
        "dish": "Grilled Chicken Bowl",
        "description": "Tender grilled chicken with quinoa, broccoli and tahini sauce",
        "protein_g": 42,
        "calories": 480,
        "price": 249,
        "rating": 4.5,
        "eta_min": 25,
        "cuisine": "Healthy",
        "tags": ["high-protein", "gluten-free"],
    },
    {
        "id": 2,
        "name": "NutriBowl",
        "dish": "Paneer Tikka Wrap",
        "description": "Marinated paneer tikka in a whole-wheat wrap with mint chutney",
        "protein_g": 28,
        "calories": 420,
        "price": 199,
        "rating": 4.2,
        "eta_min": 20,
        "cuisine": "Indian",
        "tags": ["vegetarian", "high-protein"],
    },
    {
        "id": 3,
        "name": "HealthyGrill",
        "dish": "Egg White Scramble Plate",
        "description": "6-egg white scramble with sautéed mushrooms, spinach and multigrain toast",
        "protein_g": 35,
        "calories": 320,
        "price": 179,
        "rating": 4.0,
        "eta_min": 15,
        "cuisine": "Continental",
        "tags": ["high-protein", "low-fat"],
    },
    {
        "id": 4,
        "name": "SpiceBox",
        "dish": "Dal Makhani + Rice",
        "description": "Slow-cooked black lentils in a rich tomato base, served with steamed rice",
        "protein_g": 18,
        "calories": 550,
        "price": 149,
        "rating": 4.3,
        "eta_min": 30,
        "cuisine": "Indian",
        "tags": ["vegetarian", "comfort-food"],
    },
    {
        "id": 5,
        "name": "GreenLeaf",
        "dish": "Quinoa Protein Salad",
        "description": "Quinoa, chickpeas, cucumber, cherry tomatoes with lemon-herb dressing",
        "protein_g": 22,
        "calories": 380,
        "price": 279,
        "rating": 4.6,
        "eta_min": 35,
        "cuisine": "Healthy",
        "tags": ["vegan", "high-protein"],
    },
]